# Generated by Django 4.0.4 on 2022-05-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractt',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='Date')),
                ('status', models.IntegerField(db_column='Status')),
            ],
            options={
                'db_table': 'Contractt',
                'managed': True,
            },
        ),
    ]
