# Generated by Django 4.0.4 on 2022-05-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contractt_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract_new',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('service', models.IntegerField(db_column='Service')),
                ('client', models.IntegerField(db_column='Client')),
                ('master', models.IntegerField(db_column='Master')),
                ('date', models.DateField(db_column='Date')),
                ('status', models.IntegerField(db_column='Status')),
            ],
            options={
                'db_table': 'Contract_new',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Contractt',
        ),
    ]
