# Generated by Django 4.0.4 on 2022-05-30 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract_new',
            options={'managed': False},
        ),
    ]
